export const MAKE_AGENDA = "MAKE_AGENDA";
export const DELETE_AGENDA = "DELETE_AGENDA";

export const CREATE_MEETING_REQUEST = "CREATE_MEETING_REQUEST";
export const CREATE_MEETING_SUCCESS = "CREATE_MEETING_SUCCESS";
export const CREATE_MEETING_FAILURE = "CREATE_MEETING_FAILURE";
