export const MAKE_AGENDA = "MAKE_AGENDA";
export const DELETE_AGENDA = "DELETE_AGENDA";

export const CREATE_MEETING_REQUEST = "CREATE_MEETING_REQUEST";
export const CREATE_MEETING_SUCCESS = "CREATE_MEETING_SUCCESS";
export const CREATE_MEETING_FAILURE = "CREATE_MEETING_FAILURE";

export const GET_MEETINGS_REQUEST = "GET_MEETINGS_REQUEST";
export const GET_MEETINGS_SUCCESS = "GET_MEETINGS_SUCCESS";
export const GET_MEETINGS_FAILURE = "GET_MEETINGS_FAILURE";

export const GET_MY_MEETINGS_REQUEST = "GET_MY_MEETINGS_REQUEST";
export const GET_MY_MEETINGS_SUCCESS = "GET_MY_MEETINGS_SUCCESS";
export const GET_MY_MEETINGS_FAILURE = "GET_MY_MEETINGS_FAILURE";
